import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <div className="navBar">
          <Link href="/">Home</Link>
          <Link href="/list">List</Link>
          <Link href="/vart">Cart</Link>
        </div>
        {/* children에 page.js가 들어감 */}
        {children}
      </body>
    </html>
  );
}
